spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username:
    password:
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2
auth:
  key: c2VjcmV0LWtleQ==
  token:
    expiration: 4
